const Campeones = [
    {
        id: 1,
        title: "Aatrox",
        alt: "Aatrox",
        src: "/images/Campeones/Aatrox1.jpg",
    },
    {
        id: 2,
        title: "Ahri",
        alt: "Ahri",
        src: "/images/Campeones/Ahri1.jpg",
    },
    {
        id: 3,
        title: "Akali",
        alt: "Akali",
        src: "/images/Campeones/Akali1.jpg",
    },
    {
        id: 4,
        title: "Akshan",
        alt: "Akshan",
        src: "/images/Campeones/Akshan1.jpg",
    },
    {
        id: 5,
        title: "Alistar",
        alt: "Alistar",
        src: "/images/Campeones/Alistar1.jpg",
    },
    {
        id: 6,
        title: "Amumu",
        alt: "Amumu",
        src: "/images/Campeones/Amumu1.jpg",
    },
    {
        id: 7,
        title: "Anivia",
        alt: "Anivia",
        src: "/images/Campeones/Anivia1.jpg",
    },
    {
        id: 8,
        title: "Annie",
        alt: "Annie",
        src: "/images/Campeones/Annie1.jpg",
    },
    {
        id: 9,
        title: "Aphelios",
        alt: "Aphelios",
        src: "/images/Campeones/Aphelios1.jpg",
    },
    {
        id: 10,
        title: "Ashe",
        alt: "Ashe",
        src: "/images/Campeones/Ashe1.jpg",
    },
    {
        id: 11,
        title: "AurelionSol",
        alt: "AurelionSol",
        src: "/images/Campeones/AurelionSol1.jpg",
    },
    {
        id: 12,
        title: "Azir",
        alt: "Azir",
        src: "/images/Campeones/Azir1.jpg",
    },
    {
        id: 13,
        title: "Bard",
        alt: "Bard",
        src: "/images/Campeones/Bard1.jpg",
    },
    {
        id: 14,
        title: "Belveth",
        alt: "Belveth",
        src: "/images/Campeones/Belveth1.jpg",
    },
    {
        id: 15,
        title: "Blitzcrank",
        alt: "Blitzcrank",
        src: "/images/Campeones/Blitzcrank1.jpg",
    },
    {
        id: 16,
        title: "Brand",
        alt: "Brand",
        src: "/images/Campeones/Brand1.jpg",
    },
    {
        id: 17,
        title: "Braum",
        alt: "Braum",
        src: "/images/Campeones/Braum1.jpg",
    },
    {
        id: 18,
        title: "Briar",
        alt: "Briar",
        src: "/images/Campeones/Briar1.jpg",
    },
    {
        id: 19,
        title: "Caitlyn",
        alt: "Caitlyn",
        src: "/images/Campeones/Caitlyn1.jpg",
    },
    {
        id: 20,
        title: "Camille",
        alt: "Camille",
        src: "/images/Campeones/Camille1.jpg",
    },
    {
        id: 21,
        title: "Cassiopeia",
        alt: "Cassiopeia",
        src: "/images/Campeones/Cassiopeia1.jpg",
    },
    {
        id: 22,
        title: "Chogath",
        alt: "Chogath",
        src: "/images/Campeones/Chogath1.jpg",
    },
    {
        id: 23,
        title: "Corki",
        alt: "Corki",
        src: "/images/Campeones/Corki1.jpg",
    },
    {
        id: 24,
        title: "Darius",
        alt: "Darius",
        src: "/images/Campeones/Darius1.jpg",
    },
    {
        id: 25,
        title: "Diana",
        alt: "Diana",
        src: "/images/Campeones/Diana1.jpg",
    },
    {
        id: 26,
        title: "Draven",
        alt: "Draven",
        src: "/images/Campeones/Draven1.jpg",
    },
    {
        id: 27,
        title: "DrMundo",
        alt: "DrMundo",
        src: "/images/Campeones/DrMundo1.jpg",
    },
    {
        id: 28,
        title: "Ekko",
        alt: "Ekko",
        src: "/images/Campeones/Ekko1.jpg",
    },
    {
        id: 29,
        title: "Elise",
        alt: "Elise",
        src: "/images/Campeones/Elise1.jpg",
    },
    {
        id: 30,
        title: "Evelynn",
        alt: "Evelynn",
        src: "/images/Campeones/Evelynn1.jpg",
    },
    {
        id: 31,
        title: "Ezreal",
        alt: "Ezreal",
        src: "/images/Campeones/Ezreal1.jpg",
    },
    {
        id: 32,
        title: "Fiddlesticks",
        alt: "Fiddlesticks",
        src: "/images/Campeones/Fiddlesticks1.jpg",
    },
    {
        id: 33,
        title: "Fiora",
        alt: "Fiora",
        src: "/images/Campeones/Fiora1.jpg",
    },
    {
        id: 34,
        title: "Fizz",
        alt: "Fizz",
        src: "/images/Campeones/Fizz1.jpg",
    },
    {
        id: 35,
        title: "Galio",
        alt: "Galio",
        src: "/images/Campeones/Galio1.jpg",
    },
    {
        id: 36,
        title: "Gangplank",
        alt: "Gangplank",
        src: "/images/Campeones/Gangplank1.jpg",
    },
    {
        id: 37,
        title: "Garen",
        alt: "Garen",
        src: "/images/Campeones/Garen1.jpg",
    },
    {
        id: 38,
        title: "Gnar",
        alt: "Gnar",
        src: "/images/Campeones/Gnar1.jpg",
    },
    {
        id: 39,
        title: "Gragas",
        alt: "Gragas",
        src: "/images/Campeones/Gragas1.jpg",
    },
    {
        id: 40,
        title: "Graves",
        alt: "Graves",
        src: "/images/Campeones/Graves1.jpg",
    },
    {
        id: 41,
        title: "Gwen",
        alt: "Gwen",
        src: "/images/Campeones/Gwen1.jpg",
    },
    {
        id: 42,
        title: "Hecarim",
        alt: "Hecarim",
        src: "/images/Campeones/Hecarim1.jpg",
    },
    {
        id: 43,
        title: "Heimerdinger",
        alt: "Heimerdinger",
        src: "/images/Campeones/Heimerdinger1.jpg",
    },
    {
        id: 44,
        title: "Hwei",
        alt: "Hwei",
        src: "/images/Campeones/Hwei1.jpg",
    },
    {
        id: 45,
        title: "Illaoi",
        alt: "Illaoi",
        src: "/images/Campeones/Illaoi1.jpg",
    },
    {
        id: 46,
        title: "Irelia",
        alt: "Irelia",
        src: "/images/Campeones/Irelia1.jpg",
    },
    {
        id: 47,
        title: "Ivern",
        alt: "Ivern",
        src: "/images/Campeones/Ivern1.jpg",
    },
    {
        id: 48,
        title: "Janna",
        alt: "Janna",
        src: "/images/Campeones/Janna1.jpg",
    }
];

export default Campeones;